### ISSUE TITLE
Create endpoints for the retrieval of similar annotations

### ISSUE THREAD

**Issue by bathienle** [Cytomine-ULiege/Cytomine-core#24]
# Description

Create endpoints for communicating with the CBIR server

# Task

- [x] Create communication between core and cbir server
- [x] Create endpoint for indexing an annotation crop
- [x] Create endpoint for retrieving similar annotations given one annotation crop
- [x] Create endpoint for deleting an index given one annotation crop
